["2a-emulator"]
name = ""
relPath = ""
subsystem = "rust"
translator = "cargo-lock"

["2a-emulator".subsystemInfo]
workspaceMembers = [ "emulator-2a", "emulator-2a-lib" ]

[["2a-emulator".subsystemInfo.crates]]
name = "emulator-2a"
relPath = "emulator-2a"
version = "8.2.1"

[["2a-emulator".subsystemInfo.crates]]
name = "emulator-2a-lib"
relPath = "emulator-2a-lib"
version = "0.3.4"
